# Generated by Django 2.0.3 on 2018-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180706_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='blog_user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='is_reply',
            field=models.IntegerField(default=0, verbose_name='回复'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
