# Generated by Django 2.0.3 on 2018-08-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='love',
        ),
    ]
