# Generated by Django 2.0.3 on 2018-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='notice',
            name='keywords',
            field=models.CharField(max_length=32, null=True, verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(max_length=32, null=True, verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.CharField(max_length=32, null=True, verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='type',
            name='keywords',
            field=models.CharField(max_length=32, null=True, verbose_name='关键字'),
        ),
    ]
