# Generated by Django 2.0.3 on 2018-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=16, verbose_name='验证码'),
        ),
    ]
